//go:generate go run github.com/cilium/ebpf/cmd/bpf2go -cc clang -cflags "-O2 -g -Wall -target bpf -I/usr/include -I/usr/include/x86_64-linux-gnu" Probe ./bpf/probe.c

package main

import (
	"bytes"
	"encoding/binary"
	"encoding/json"
	"flag"
	"fmt"
	"net"
	"os"
	"os/signal"
	"syscall"
	"time"

	"github.com/cilium/ebpf"
	"github.com/cilium/ebpf/ringbuf"
)

func main() {
	mode    := flag.String("mode", "audit", "disabled|audit|block")
	policy  := flag.String("policy", "", "path to payloadguard-policy.yaml")
	dryRun  := flag.Bool("dry-run", false, "load BPF objects and print events without acting")
	outPath := flag.String("out", "pg-runtime-events.json", "event log output path")
	flag.Parse()

	if *mode == "disabled" {
		os.Exit(0)
	}

	if !preflight() {
		os.Setenv("PAYLOADGUARD_RUNTIME", "disabled")
		os.Exit(0)
	}

	al, err := LoadPolicy(*policy)
	if err != nil {
		warn("policy load error: " + err.Error())
	}

	// Load pre-compiled BPF objects (generated by bpf2go from bpf/probe.c)
	objs := ProbeObjects{}
	loadOpts := &ebpf.CollectionOptions{
		Programs: ebpf.ProgramOptions{LogLevel: ebpf.LogLevelInstruction},
	}
	if err := LoadProbeObjects(&objs, loadOpts); err != nil {
		warn("LoadProbeObjects: " + err.Error())
		os.Exit(0)
	}
	defer objs.Close()

	// Push agent mode into BPF pg_config map: 0=audit, 1=block
	modeVal := uint32(0)
	if *mode == "block" {
		modeVal = 1
	}
	configKey := uint32(0)
	if err := objs.PgConfig.Put(configKey, modeVal); err != nil {
		warn("PgConfig.Put: " + err.Error())
	}

	// Push allowed IPv4 addresses into BPF egress_allow_ipv4 map
	for ipStr := range al.IPs {
		ip4 := net.ParseIP(ipStr).To4()
		if ip4 == nil {
			continue // skip IPv6 for now
		}
		key := binary.BigEndian.Uint32(ip4)
		val := uint8(1)
		if err := objs.EgressAllowIpv4.Put(key, val); err != nil {
			warn("EgressAllowIpv4.Put " + ipStr + ": " + err.Error())
		}
	}

	// Attach all four tracepoints
	links, err := attachAll(&objs)
	if err != nil {
		warn("attach: " + err.Error())
		os.Exit(0)
	}
	defer closeLinks(links)

	// Open ring buffer reader
	rd, err := ringbuf.NewReader(objs.Events)
	if err != nil {
		warn("ringbuf.NewReader: " + err.Error())
		os.Exit(0)
	}
	defer rd.Close()

	// Open output file
	out, err := os.Create(*outPath)
	if err != nil {
		warn("cannot create output file: " + err.Error())
		os.Exit(0)
	}
	defer out.Close()

	// Graceful SIGTERM / SIGINT handler
	sig := make(chan os.Signal, 1)
	signal.Notify(sig, syscall.SIGTERM, syscall.SIGINT)
	go func() {
		<-sig
		rd.Close()
	}()

	fmt.Fprintf(os.Stderr, "::notice::pg-agent running in %s mode (dry-run=%v)\n",
		*mode, *dryRun)

	for {
		rec, err := rd.Read()
		if err != nil {
			break
		}
		if len(rec.RawSample) < binary.Size(Event{}) {
			continue
		}

		var e Event
		binary.Read(bytes.NewReader(rec.RawSample), binary.LittleEndian, &e)

		entry := map[string]any{
			"time":    time.Now().UTC().Format(time.RFC3339),
			"type":    eventTypeName(e.Type),
			"pid":     e.Pid,
			"comm":    e.CommStr(),
			"detail":  e.DetailStr(),
			"mode":    *mode,
			"dry_run": *dryRun,
			"blocked": e.Blocked == 1,
		}
		line, err := json.Marshal(entry)
		if err != nil {
			continue
		}
		fmt.Fprintln(out, string(line))
		fmt.Fprintln(os.Stdout, string(line))
	}
}
