// Code generated by bpf2go; DO NOT EDIT.
//go:build mips || mips64 || ppc64 || s390x

package main

import (
	"bytes"
	_ "embed"
	"fmt"
	"io"

	"github.com/cilium/ebpf"
)

// LoadProbe returns the embedded CollectionSpec for Probe.
func LoadProbe() (*ebpf.CollectionSpec, error) {
	reader := bytes.NewReader(_ProbeBytes)
	spec, err := ebpf.LoadCollectionSpecFromReader(reader)
	if err != nil {
		return nil, fmt.Errorf("can't load Probe: %w", err)
	}

	return spec, err
}

// LoadProbeObjects loads Probe and converts it into a struct.
//
// The following types are suitable as obj argument:
//
//	*ProbeObjects
//	*ProbePrograms
//	*ProbeMaps
//
// See ebpf.CollectionSpec.LoadAndAssign documentation for details.
func LoadProbeObjects(obj interface{}, opts *ebpf.CollectionOptions) error {
	spec, err := LoadProbe()
	if err != nil {
		return err
	}

	return spec.LoadAndAssign(obj, opts)
}

// ProbeSpecs contains maps and programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProbeSpecs struct {
	ProbeProgramSpecs
	ProbeMapSpecs
	ProbeVariableSpecs
}

// ProbeProgramSpecs contains programs before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProbeProgramSpecs struct {
	TraceConnect *ebpf.ProgramSpec `ebpf:"trace_connect"`
	TraceExecve  *ebpf.ProgramSpec `ebpf:"trace_execve"`
	TraceOpenat  *ebpf.ProgramSpec `ebpf:"trace_openat"`
	TracePtrace  *ebpf.ProgramSpec `ebpf:"trace_ptrace"`
}

// ProbeMapSpecs contains maps before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProbeMapSpecs struct {
	Ancestry        *ebpf.MapSpec `ebpf:"ancestry"`
	EgressAllowIpv4 *ebpf.MapSpec `ebpf:"egress_allow_ipv4"`
	Events          *ebpf.MapSpec `ebpf:"events"`
	PgConfig        *ebpf.MapSpec `ebpf:"pg_config"`
	WorkerPid       *ebpf.MapSpec `ebpf:"worker_pid"`
}

// ProbeVariableSpecs contains global variables before they are loaded into the kernel.
//
// It can be passed ebpf.CollectionSpec.Assign.
type ProbeVariableSpecs struct {
}

// ProbeObjects contains all objects after they have been loaded into the kernel.
//
// It can be passed to LoadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProbeObjects struct {
	ProbePrograms
	ProbeMaps
	ProbeVariables
}

func (o *ProbeObjects) Close() error {
	return _ProbeClose(
		&o.ProbePrograms,
		&o.ProbeMaps,
	)
}

// ProbeMaps contains all maps after they have been loaded into the kernel.
//
// It can be passed to LoadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProbeMaps struct {
	Ancestry        *ebpf.Map `ebpf:"ancestry"`
	EgressAllowIpv4 *ebpf.Map `ebpf:"egress_allow_ipv4"`
	Events          *ebpf.Map `ebpf:"events"`
	PgConfig        *ebpf.Map `ebpf:"pg_config"`
	WorkerPid       *ebpf.Map `ebpf:"worker_pid"`
}

func (m *ProbeMaps) Close() error {
	return _ProbeClose(
		m.Ancestry,
		m.EgressAllowIpv4,
		m.Events,
		m.PgConfig,
		m.WorkerPid,
	)
}

// ProbeVariables contains all global variables after they have been loaded into the kernel.
//
// It can be passed to LoadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProbeVariables struct {
}

// ProbePrograms contains all programs after they have been loaded into the kernel.
//
// It can be passed to LoadProbeObjects or ebpf.CollectionSpec.LoadAndAssign.
type ProbePrograms struct {
	TraceConnect *ebpf.Program `ebpf:"trace_connect"`
	TraceExecve  *ebpf.Program `ebpf:"trace_execve"`
	TraceOpenat  *ebpf.Program `ebpf:"trace_openat"`
	TracePtrace  *ebpf.Program `ebpf:"trace_ptrace"`
}

func (p *ProbePrograms) Close() error {
	return _ProbeClose(
		p.TraceConnect,
		p.TraceExecve,
		p.TraceOpenat,
		p.TracePtrace,
	)
}

func _ProbeClose(closers ...io.Closer) error {
	for _, closer := range closers {
		if err := closer.Close(); err != nil {
			return err
		}
	}
	return nil
}

// Do not access this directly.
//
//go:embed probe_bpfeb.o
var _ProbeBytes []byte
